[theme]
# Light/dark mode can be "light", "dark", or "auto"
base = "light"

[browser]
# Whether to show the address bar
gatherUsageStats = false

[client]
# Whether to enable the toolbar
toolbarMode = "auto"

[server]
# Since we don't have a static folder yet, disable static serving
enableStaticServing = false
enableXsrfProtection = true
# Enable auto-reloading
runOnSave = true
# Set file watcher type
fileWatcherType = "poll"

[logger]
level = "info"
